### PR TITLE
Help wanted: Typescript rewrite

### PR DESCRIPTION
**Pull request by estevanmaito**
So, I've been working on it for the past weeks and got to a point where I'm not able to make progress anymore, and I think more experienced TS devs will find a way to fix this.

Some tests are now broken because I've made some rules stricter, like the requirement of `children` for some components, and I'll work to make those pass, but this is very simple.

## Where your help is needed

There are 2 components that are broken and need attention: `Button` and `Pagination` (most `Pagination` problems exist because of `Button` problems 🤷‍♂️).

I've also placed some comments (`// NEEDS REVIEW`) around where I think things could be different.

## Final question

Before the refactoring, for a `Button`, I was destructuring all props, so you could create a `Button` with any event handler like `onClick`, `onMouseEnter`, etc. and those props weren't present inside `PropTypes`. ✅

Now, as you'll find in the tests, even using `onClick` will result in errors because it's obviously not part of the component `interface`. ❌

Do I really need to put all possible event handlers inside the `interface`? Is this the only possibility and is it so obvious that I cannot find any material talking about it?

### CODE REVIEW

**Comment by gillisandrew** [comment]
You'll probably need to call `React.createElement` to get typescript working properly on the string to element conversion. To add all the event handler attributes you extend the props interface from `React.HTMLAttributes`.

**Comment by HerbCaudill** [comment]
Hey, Estevan. Sorry I didn't see your update until just now. 

> using onClick will result in errors because it's obviously not part of the component interface

In general what you want to do is have your props extend the attributes of whatever React element you'll be spreading the props over with `{...other}`. That way you get all the underlying element's props for free, including `className` and `children`, plus all of its event handlers like `onClick`. 

 So for example in Backdrop.tsx where you have this:

https://github.com/estevanmaito/windmill-react-ui/blob/7eaf1089b2f9191e6267724dae49fedd64c4f99e/src/Backdrop.tsx#L7-L11

Since you're spreading `{...other}` over a `<div>` element, you can just do this:

```tsx
interface Props extends React.HTMLAttributes<HTMLDivElement> {
  // we don't need to list `children`, `className`, or `onClick` because they're all <div> attributes
}
```
 
Your `Props` interface only needs to explicitly list your component's non-HTML attributes (or attributes that you're passing to a different element). So for example in the `Avatar` component you'd do this: 

```tsx
interface Props extends React.HTMLAttributes<HTMLDivElement> {
  size?: 'large' | 'regular' | 'small' // custom attribute
  alt?: string // this is going to the <img>, not the <div>
  src: string // this is going to the <img>, not the <div>
}

const Avatar = React.forwardRef<HTMLDivElement, Props>(function Avatar(props, ref) {
  const { size = 'regular', src, alt, className, ...other } = props
  // ...
  return (
    <div className={cls} ref={ref} {...other}>
      <img className="object-cover w-full h-full rounded-full" src={src} alt={alt} loading="lazy" />
      <div className="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
    </div>
  )
})
```

I've made all these changes and have all tests passing - PR to follow. 

image

**Comment by HerbCaudill** [comment]
> Some tests are now broken because I've made some rules stricter, like the requirement of children for some components, and I'll work to make those pass, but this is very simple.

I just noticed this comment - if you do want to make `children` required in a component, you would need to add it to the Props interface (and then provide dummy contents in the test).

**Comment by ronyfhebrian** [comment]
any update on Typescript format?

**Comment by estevanmaito** [comment]
@ronyfhebrian 

https://github.com/estevanmaito/windmill-react-ui/pull/15#pullrequestreview-512200192

soon

**Pull request closed without merging**
